In [4]:
import numpy as np
from PIL import Image
import os
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
rootDir = 'photos'
arr = np.zeros([20, 200, 200, 3])
def main(): 
    try:
        def num_of_files():
            try:
                for dirName, subdirList, fileList in os.walk(rootDir):
                    fileCount_ = len(fileList)
                print("Total number of files: ",fileCount_)
            except FileNotFoundError:
                print("Sorry file not found.")        
            ################################################################        
        def find_dir():
            try:
                for dirName, subdirList, fileList in os.walk(rootDir):
                    print('Found directory: %s' % dirName)
                    for fname in fileList:
                        print('\t%s' % fname)
            except FileNotFoundError:
                print("Sorry file not found.")
            ############################################
        def img_resize():
            try:
                i=0
                for dirName, subdirList, fileList in os.walk(rootDir):
                    for fname in fileList:
                        filepath = dirName+os.sep+fname
                        if filepath.endswith('.jpg'):
                                img = Image.open(filepath)
                                img_n = img.resize((200,200))
                                arr[i]= img_n
                                i+=1
                print(arr)
            except FileNotFoundError:
                print("Sorry file not found.")
        print(num_of_files())
        print(find_dir())
        print('Numpy Array of resized images :')
        print(img_resize())
        
        ##################################################
    except RuntimeError:
        print("Found an error !")
##########################################################        
if __name__ == '__main__':
    main()

Total number of files:  20
None
Found directory: photos
	1.jpg
	10.jpg
	11.jpg
	12.jpg
	13.jpg
	14.jpg
	15.jpg
	16.jpg
	17.jpg
	18.jpg
	19.jpg
	2.jpg
	20.jpg
	3.jpg
	4.jpg
	5.jpg
	6.jpg
	7.jpg
	8.jpg
	9.jpg
None
Numpy Array of resized images :
[[[[ 96.  80. 151.]
   [ 97.  83. 158.]
   [107.  89. 165.]
   ...
   [ 46.  67. 146.]
   [ 44.  66. 142.]
   [ 40.  59. 135.]]

  [[ 98.  81. 152.]
   [101.  85. 160.]
   [105.  87. 163.]
   ...
   [ 45.  66. 149.]
   [ 43.  64. 145.]
   [ 43.  62. 139.]]

  [[100.  82. 156.]
   [105.  84. 163.]
   [108.  92. 167.]
   ...
   [ 48.  69. 152.]
   [ 44.  65. 146.]
   [ 43.  62. 139.]]

  ...

  [[ 42.  38.  75.]
   [ 49.  43. 103.]
   [ 39.  26.  79.]
   ...
   [ 26.  16.  43.]
   [ 30.  16.  42.]
   [ 26.  17.  44.]]

  [[ 40.  32.  81.]
   [ 70.  71. 128.]
   [ 74.  77. 122.]
   ...
   [ 22.   9.  35.]
   [ 26.  13.  39.]
   [ 26.  16.  43.]]

  [[ 35.  32.  79.]
   [ 79.  77. 142.]
   [ 68.  72. 135.]
   ...
   [ 17.   5.  29.]
   [ 20.   8.  32