In [5]:
import numpy as np
from PIL import Image
# Import the os module, for the os.walk function
import os
# Set the directory you want to start from
rootDir = 'numpy-photos'
arr = np.zeros([20, 200, 200])
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
        filepath = dirName+os.sep+fname
        if filepath.endswith('.jpg'):
            print("resized photoes")
            img = Image.open(filepath)
            img = img.resize((200,200))
            print(img)
            arr = np.array(img)
            print("3-dimentional array :")
            print(arr)

Found directory: numpy-photos
	1.jpg
resized photoes
<PIL.Image.Image image mode=RGB size=200x200 at 0x2C25FC6FB00>
3-dimentional array :
[[[ 96  80 151]
  [ 97  83 158]
  [107  89 165]
  ...
  [ 46  67 146]
  [ 44  66 142]
  [ 40  59 135]]

 [[ 98  81 152]
  [101  85 160]
  [105  87 163]
  ...
  [ 45  66 149]
  [ 43  64 145]
  [ 43  62 139]]

 [[100  82 156]
  [105  84 163]
  [108  92 167]
  ...
  [ 48  69 152]
  [ 44  65 146]
  [ 43  62 139]]

 ...

 [[ 42  38  75]
  [ 49  43 103]
  [ 39  26  79]
  ...
  [ 26  16  43]
  [ 30  16  42]
  [ 26  17  44]]

 [[ 40  32  81]
  [ 70  71 128]
  [ 74  77 122]
  ...
  [ 22   9  35]
  [ 26  13  39]
  [ 26  16  43]]

 [[ 35  32  79]
  [ 79  77 142]
  [ 68  72 135]
  ...
  [ 17   5  29]
  [ 20   8  32]
  [ 18   6  28]]]
	10.jpg
resized photoes
<PIL.Image.Image image mode=RGB size=200x200 at 0x2C25FC8DCF8>
3-dimentional array :
[[[  3   1   4]
  [ 32  37  17]
  [  4  31  14]
  ...
  [ 62  88  43]
  [  1  23   0]
  [ 16  28  16]]

 [[ 19  41   5]
  [

<PIL.Image.Image image mode=RGB size=200x200 at 0x2C25FC6FB00>
3-dimentional array :
[[[ 52  89 195]
  [ 50  89 194]
  [ 49  86 192]
  ...
  [  8  50 150]
  [ 10  52 154]
  [ 10  49 150]]

 [[ 54  92 193]
  [ 50  87 193]
  [ 52  89 196]
  ...
  [ 14  56 156]
  [ 10  52 152]
  [ 11  50 153]]

 [[ 55  93 194]
  [ 53  91 192]
  [ 54  91 195]
  ...
  [ 15  57 157]
  [ 15  57 157]
  [ 15  55 153]]

 ...

 [[ 56  65 104]
  [ 58  67 108]
  [ 59  68 109]
  ...
  [ 60  69 110]
  [ 54  65 110]
  [ 57  64 110]]

 [[ 55  64 103]
  [ 59  68 109]
  [ 61  70 111]
  ...
  [ 63  72 113]
  [ 48  59 104]
  [ 51  58 104]]

 [[ 55  63 102]
  [ 60  68 107]
  [ 56  65 106]
  ...
  [ 72  79 121]
  [ 64  71 115]
  [ 63  70 112]]]
	5.jpg
resized photoes
<PIL.Image.Image image mode=RGB size=200x200 at 0x2C25FC6FB00>
3-dimentional array :
[[[ 42  65  71]
  [ 46  65  72]
  [ 49  63  72]
  ...
  [250 216 142]
  [255 223 142]
  [255 221 140]]

 [[ 46  65  69]
  [ 48  66  70]
  [ 49  64  69]
  ...
  [254 207 137]
  [